name: Acceptance Test Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github_original/workflows/acctest-terraform-lint.yml
      - .go-version
      - .ci_original/.tflint.hcl
      - .ci_original/scripts/validate-terraform.sh
      - .ci_original/tools/go.mod
      - 'internal/service/**/*_test.go'

jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - run: cd .ci_original/tools && go install github.com/katbyte/terrafmt

      - run: |
          find ./internal/service -type f -name '*_test.go' \
            | sort -u \
            | xargs -I {} terrafmt diff --check --fmtcompat {}

  tflint:
    name: Validate Acceptance Tests
    runs-on: [custom, linux, medium]
    strategy:
      matrix:
        path: ['[a-f]', '[g-z]']
    env:
      TEST_FILES_PARTITION: '\./internal/service/${{ matrix.path }}.*/.*_test\.go'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - uses: actions/cache@v3
        name: Cache plugin dir
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci_original/.tflint.hcl') }}

      - run: cd .ci_original/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci_original/tools && go install github.com/terraform-linters/tflint

      - run: tflint --config .ci_original/.tflint.hcl --init

      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION }} | wc -l | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION }} \
            | .ci/scripts/validate-terraform.sh
